# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-25 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotpost',
            name='spot_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spot_poster', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
